sudo: false

language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - wkhtmltopdf # qweb reports, report_webkit

cache:
  directories:
    - parts
    - eggs

virtualenv:
  system_site_packages: true

before_install:
  - git config --global user.name "TravisCI"
  - git config --global user.email "travis@camptocamp.com"

env:
  matrix:
    - LINT_CHECK="1"
    - SCENARIO="1"
    - TESTS="1"
  global:
    - SCENARIO="0" TESTS="0" LINT_CHECK="0"
    - ADDONS_DIR=${TRAVIS_BUILD_DIR}/specific-parts/specific-addons

install:
  - if [[ "$SCENARIO" == "1" || "$TESTS" == "1" ]] ; then npm install -g less less-plugin-clean-css ; fi
  - if [[ "$SCENARIO" == "1" || "$TESTS" == "1" ]] ; then ${TRAVIS_BUILD_DIR}/bootstrap.sh profiles/travis.cfg ; fi
  - if [[ "$SCENARIO" == "1" || "$TESTS" == "1" ]] ; then ${TRAVIS_BUILD_DIR}/bin/buildout ; fi
  - if [ "$LINT_CHECK" == "1" ] ; then pip install -q flake8 ; fi

before_script:
  - if [ "$TESTS" == "1" ] ; then export specific_addons=$(find ${ADDONS_DIR}/* -maxdepth 0 -type d -and -not -name server_environment_files -printf "%f\n" | awk -vORS=, '{print $1}' | sed 's/,$/\n/') ; fi

script:
  - if [ "$LINT_CHECK" == "1" ] ; then flake8 ${ADDONS_DIR} --exclude=__init__.py ; fi
  - if [ "$SCENARIO" == "1" ] ; then bin/oerpscenario -t swisslux -t setup -t ~slow ; fi
  - if [ "$SCENARIO" == "1" ] ; then bin/oerpscenario -t upgrade_from_9.0.11 -t ~slow ; fi
  - if [ "$TESTS" == "1" ] ; then bin/start_openerp --stop-after-init --workers=0 --without-demo=False -i ${specific_addons} ; fi
  - if [ "$TESTS" == "1" ] ; then bin/runtests --log-handler=openerp.netsvc:DEBUG --log-handler=openerp.tools.yaml_import:DEBUG -u ${specific_addons} ; fi
